### ISSUE TITLE
Formatting CSS code - Opening brace on same line option?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [trullock/NUglify#188]
Expected formatting:
```html
hr {
	height: 4px;
	background-color: #6cf;
	border: 0;
	width: 100%
}
```

Current formatting:
```html
hr
{
	height: 4px;
	background-color: #6cf;
	border: 0;
	width: 100%
}
```

Related to: https://github.com/trullock/NUglify/issues/187

**Comment by trullock** [comment]
You want to use this setting:

`public BlockStart BlocksStartOnSameLine { get; set; }`

Technically this ticket is solved because you can use that ^ but I'm going to treat this ticket as the impetus to improve the `Settings` object generally and make OutputMode more obvious to interact with

Theres too many misc `bool`s to magically configure
