### ISSUE TITLE
Double hyphen in html comment

### ISSUE THREAD

**Issue by jsmorgan** [trullock/NUglify#73]
I stumbled on this sort of accidentally when testing with NUglify. We had a comment of the form: 
`<!-- <div class="block__element--modifier">something</div> -->` 
This causes the parser to see everything after the "--" as valid, uncommented code and autocloses tags prematurely. Looking at the [HTML5 ](https://www.w3.org/TR/html52/syntax.html#comments) spec it looks like "--" should now be valid. I think I've identified a potential fix for the parser, but wanted to verify this is still the intended behavior before submitting a PR.

**Comment by trullock** [comment]
Its a bit unclear which way around you're saying the issue is. I assume you mean NUglify is only treating `<!-- <div class="block__element--` as the comment, and then `modifier">something</div> -->` as being after the comment?

Either way, the `--` in your BEM shouldn't be treated at anything to do with the comment enclosing tokens.

Send that PR! :)
